# 開発用Dockerfile
FROM node:18-slim

# 作業ディレクトリの設定
WORKDIR /usr/src/app

# 依存関係のコピー
COPY package*.json ./

# 依存関係のインストール
RUN npm install

# ホストのファイルはボリュームマウントするため、ここではコピーしない

# 開発サーバーの起動
CMD ["npm", "run", "dev"]
